DOSSIER_META = {
    "sektor": "München Nord-West",
    "sektor_code": "MNW",
    "kw": "KW 14 / 2026",
    "kw_num": 14,
    "year": 2026,
    "signal_count": 12,
    "signal_count_hoch": 4,
    "dossier_id": "BSG-MNW-2026-14-0042",
}

SIGNALE = [
    {
        "relevanz": "hoch",
        "titel": "Aufstellungsbeschluss Bebauungsplan Nr. 2147 — Gewerbegebiet Feldmoching-Hasenbergl",
        "quelle": "Stadtrat München",
        "datum": "18.03.2026",
        "typ": "Bebauungsplan",
        "nutzung": "Gewerbe / Mixed-Use",
        "quellen_link_text": "Stadtrat München — Beschlussvorlage Nr. 20-26/V 12847",
        "quellen_link_url": "https://risi.muenchen.de/risi/vorlage/detail/7654321",
        "text": "Aufstellungsbeschluss für 4,2 Hektar Mischnutzung nördlich der Feldmochinger Straße. GFZ bis 1,8, Öffentlichkeitsbeteiligung Q3/2026.",
    },
    {
        "relevanz": "hoch",
        "titel": "Flächennutzungsplan-Änderung Nr. 89 — Umwidmung Agrarfläche Karlsfeld",
        "quelle": "Landratsamt Dachau",
        "datum": "22.03.2026",
        "typ": "Flächennutzung",
        "nutzung": "Wohnen",
        "quellen_link_text": "Landratsamt Dachau — Bekanntmachung FNP-Änderung Nr. 89",
        "quellen_link_url": "https://www.landratsamt-dachau.de/bekanntmachungen/fnp-89",
        "text": "6,8 Hektar südlich der B304 werden von Agrarfläche zu Wohnbaufläche umgewidmet. Bebauungsplan-Verfahren voraussichtlich Herbst 2026.",
    },
    {
        "relevanz": "hoch",
        "titel": "Städtebaulicher Wettbewerb Oberwiesenfeld-Nord",
        "quelle": "Referat für Stadtplanung München",
        "datum": "25.03.2026",
        "typ": "Wettbewerb",
        "nutzung": "Wohnen / Gewerbe",
        "quellen_link_text": "Referat für Stadtplanung — Auslobung Wettbewerb Nr. 2026-07",
        "quellen_link_url": "https://risi.muenchen.de/risi/vorlage/detail/7654400",
        "text": "Städtebaulicher Wettbewerb für 8,5 Hektar am Oberwiesenfeld. Bis zu 1.200 Wohneinheiten und Quartierszentrum geplant.",
    },
    {
        "relevanz": "hoch",
        "titel": "Vorkaufsrechtssatzung Allach-Untermenzing erweitert",
        "quelle": "Stadtrat München",
        "datum": "19.03.2026",
        "typ": "Satzung",
        "nutzung": "Wohnen",
        "quellen_link_text": "Stadtrat München — Sitzungsvorlage Nr. 20-26/V 12903",
        "quellen_link_url": "https://risi.muenchen.de/risi/vorlage/detail/7654500",
        "text": "Erweiterung der Vorkaufsrechtssatzung auf drei zusätzliche Gebiete in Allach-Untermenzing. Betrifft ca. 12 Hektar.",
    },
    {
        "relevanz": "mittel",
        "titel": "Machbarkeitsstudie S-Bahn-Verlängerung Dachau–Petershausen",
        "quelle": "Bayer. Staatsministerium für Wohnen, Bau und Verkehr",
        "datum": "20.03.2026",
        "typ": "Infrastruktur",
        "nutzung": "ÖPNV / Verkehr",
        "quellen_link_text": "StMB — Pressemitteilung Nr. 78/2026",
        "quellen_link_url": "https://www.stmb.bayern.de/med/pressemitteilungen/pm-78-2026.htm",
        "text": "Drei Trassenvarianten für die S2-Verlängerung werden untersucht. Wertsteigerungspotenzial entlang potenzieller Haltestellen.",
    },
    {
        "relevanz": "mittel",
        "titel": "Änderung des Flächennutzungsplans — Erweiterung Gewerbegebiet Bergkirchen",
        "quelle": "Amtsblatt Dachau",
        "datum": "15.03.2026",
        "typ": "Flächennutzung",
        "nutzung": "Gewerbe / Logistik",
        "quellen_link_text": "Amtsblatt Nr. 12/2026 — Gemeinde Bergkirchen",
        "quellen_link_url": "https://www.bergkirchen.de/amtsblatt/2026-12",
        "text": "Erweiterung des Gewerbegebiets um 3,1 Hektar. Öffentliche Auslegung ab 01.04.2026.",
    },
    {
        "relevanz": "mittel",
        "titel": "Neubau Grundschule und Kita Ludwigsfeld",
        "quelle": "Referat für Bildung und Sport München",
        "datum": "17.03.2026",
        "typ": "Soziale Infrastruktur",
        "nutzung": "Bildung",
        "quellen_link_text": "RBS München — Projektbeschluss Nr. RBS-2026-0412",
        "quellen_link_url": "https://risi.muenchen.de/risi/vorlage/detail/7654600",
        "text": "Neubau einer dreizügigen Grundschule mit Kita auf 1,8 Hektar in Ludwigsfeld. Baubeginn voraussichtlich Q1/2027.",
    },
    {
        "relevanz": "mittel",
        "titel": "Lärmaktionsplan Autobahn A99 — Abschnitt Feldmoching",
        "quelle": "Landratsamt München",
        "datum": "21.03.2026",
        "typ": "Umwelt",
        "nutzung": "Lärmschutz",
        "quellen_link_text": "Landratsamt München — Bekanntmachung LAP A99",
        "quellen_link_url": "https://www.landkreis-muenchen.de/bekanntmachungen/lap-a99",
        "text": "Neue Lärmschutzmaßnahmen entlang der A99 können Bauauflagen in angrenzenden Gebieten verschärfen.",
    },
]

RADAR = [
    {
        "titel": "Bürgerinitiative gegen Verdichtung in Oberschleißheim",
        "quelle": "Gemeinderat Oberschleißheim · Diskussion am 02.04.2026",
        "quellen_link_text": "Gemeinderat Oberschleißheim — Sitzungsprotokoll 14/2026",
        "quellen_link_url": "https://www.oberschleissheim.de/ratsinformation/sitzung/2026-14",
        "text": "Gemeinderat diskutiert Einwände gegen geplante Nachverdichtung im Ortszentrum.",
    },
    {
        "titel": "Voranfrage Hotelneubau am Dachauer Bahnhof",
        "quelle": "Stadt Dachau · Informell, kein förmliches Verfahren",
        "quellen_link_text": "Stadt Dachau — Bauausschuss-Sitzung 22.03.2026",
        "quellen_link_url": "https://www.dachau.de/ratsinformation/bauausschuss/2026-03",
        "text": "Noch kein förmlicher Antrag — Bauvoranfrage im Gespräch mit der Stadtverwaltung.",
    },
    {
        "titel": "Regionalplanänderung Siedlungsschwerpunkte Münchner Norden",
        "quelle": "Regierung von Oberbayern · Prüfphase",
        "quellen_link_text": "Regierung von Oberbayern — Regionalplan-Fortschreibung 2026",
        "quellen_link_url": "https://www.regierung.oberbayern.bayern.de/regionalplan/fortschreibung-2026",
        "text": "Potenzielle Neudefinition der Siedlungsschwerpunkte — betrifft langfristig Baulandausweisung.",
    },
]
